otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.endpoint=http://127.0.0.1:4318
otel.exporter.otlp.protocol=http/protobuf
otel.propagators=tracecontext,baggage
otel.instrumentation.logback-mdc.enabled=true
otel.javaagent.logging=simple
